# Generated by Django 3.0.6 on 2020-05-16 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criminal_stuff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminal',
            name='crimes',
        ),
        migrations.AddField(
            model_name='criminal',
            name='booked_at_police_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criminal',
            name='booked_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='crime_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='crime_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CrimeCommitted',
        ),
    ]
