# Generated by Django 3.0.6 on 2020-05-16 19:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_stuff', '0002_auto_20200516_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='image_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
