# Generated by Django 3.0.6 on 2020-05-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policestationprofile',
            old_name='user',
            new_name='profile',
        ),
    ]
